version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - GOLF_API_BASE_URL=${GOLF_DATA_API_BASE_URL}
      - GOLF_API_KEY=${GOLF_DATA_API_KEY}
    depends_on:
      - db
    
  client-web:
    build: ./client-web
    command: npm run dev
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=${API_BASE_URL}
      - VITE_APP_NAME=${APP_NAME}
    depends_on:
      - backend