services:
  db:
    image: postgres:17.9
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /code/backend
          initial_sync: true
          ignore:
            - .pytest_cache
            - .vscode
            - __pycache__
        - action: rebuild
          path: ./backend/requirements.txt
    ports:
      - "8000:8000"
    environment:
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - GOLF_API_BASE_URL=${GOLF_DATA_API_BASE_URL}
      - GOLF_API_KEY=${GOLF_DATA_API_KEY}
    depends_on:
      - db
  
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq
      - ./data/rabbitmq/log:/var/log/rabbitmq
  
  celery_worker:
    restart: always
    build: ./backend
    command: celery -A one_n_done_api worker -l INFO
    volumes:
      - ./backend:/code/backend
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - backend
      - rabbitmq
  
  client_web:
    build: ./client-web
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./client-web
          target: /code/client-web
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client-web/package.json
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=${API_BASE_URL}
      - VITE_APP_NAME=${APP_NAME}
    depends_on:
      - backend