# Generated by Django 4.2.5 on 2023-12-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgolfer',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentgolfer',
            name='prize_money',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
