# Generated by Django 5.0.1 on 2024-02-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='year',
        ),
        migrations.AddField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
