# Generated by Django 4.2.5 on 2023-09-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golfer',
            old_name='playerId',
            new_name='player_id',
        ),
    ]
