# Generated by Django 4.2.5 on 2023-09-15 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0002_rename_playerid_golfer_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('purse', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='golfer',
            name='country',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z .,]+$')]),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z .]+$')]),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='player_id',
            field=models.PositiveIntegerField(),
        ),
    ]
