# Generated by Django 4.2.5 on 2023-12-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0002_tournamentgolfer_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentgolfer',
            name='deleted_by_cascade',
        ),
    ]
