# Generated by Django 5.0.6 on 2025-03-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0003_remove_pick_unique_user_tournament_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='registration_cutoff',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
