# Generated by Django 5.0.6 on 2024-09-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0003_remove_pick_unique_user_tournament_season_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golferseason',
            options={'ordering': ['created'], 'verbose_name': 'Golfer Season', 'verbose_name_plural': 'Golfer Seasons'},
        ),
        migrations.AlterModelOptions(
            name='tournamentgolfer',
            options={'ordering': ['created'], 'verbose_name': 'Tournament Golfer', 'verbose_name_plural': 'Tournament Golfers'},
        ),
        migrations.AlterModelOptions(
            name='tournamentseason',
            options={'ordering': ['created'], 'verbose_name': 'Tournament Season', 'verbose_name_plural': 'Tournament Seasons'},
        ),
        migrations.AlterModelOptions(
            name='userseason',
            options={'ordering': ['created'], 'verbose_name': 'User Season', 'verbose_name_plural': 'User Seasons'},
        ),
    ]
