# Generated by Django 4.2.5 on 2023-12-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0003_remove_tournamentgolfer_deleted_by_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgolfer',
            name='position',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tournamentgolfer',
            name='prize_money',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
