# Generated by Django 5.0.1 on 2024-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0003_tournamentseason_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='alias',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
