# Generated by Django 4.2.5 on 2023-09-15 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0003_tournament_alter_golfer_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentGolfer',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('place', models.SmallIntegerField()),
                ('prize_money_won', models.PositiveIntegerField()),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='golf_pickem.golfer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golfers', to='golf_pickem.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Golfer',
                'verbose_name_plural': 'Tournament Golfers',
                'ordering': ['created'],
            },
        ),
    ]
