# Generated by Django 4.2.5 on 2024-01-12 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0004_alter_tournamentgolfer_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgolfer',
            name='golfer_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='golf_pickem.golferseason'),
        ),
        migrations.AlterField(
            model_name='tournamentgolfer',
            name='tournament_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='golf_pickem.tournamentseason'),
        ),
    ]
