# Generated by Django 4.2.5 on 2023-09-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0004_tournamentgolfer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='golfer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('player_id',), name='unique_active_player_id'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('name', 'year'), name='unique_active_name_year'),
        ),
    ]
