# Generated by Django 4.2.5 on 2023-09-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0005_golfer_unique_active_player_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tournamentgolfer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('tournament', 'golfer'), name='unique_active_tournament_golfer'),
        ),
    ]
