# Generated by Django 4.2.5 on 2023-09-17 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf_pickem', '0006_tournamentgolfer_unique_active_tournament_golfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tournament_golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_by_history', to='golf_pickem.tournamentgolfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Picks',
                'verbose_name_plural': 'Picks',
                'ordering': ['created'],
            },
        ),
    ]
