# Generated by Django 4.2.5 on 2023-09-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_pickem', '0007_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='tournament_golfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_by', to='golf_pickem.tournamentgolfer'),
        ),
    ]
